In [1]:
import pandas as pd

In [2]:
df = pd.read_csv('Campionato.csv', sep=';')

In [3]:
df.head()

,Championship,DayWeek,DayMonth,Month,Home,Away,GoalHome,GoalAway,Win,Draw,...,AwayGoal_1_match_Ago,AwayGoal_2_match_Ago,AwayGoal_3_match_Ago,AwayGoal_4_match_Ago,AwayGoal_5_match_Ago,AwayGoal_1_match_Ago_InAway,AwayGoal_2_match_Ago_InAway,AwayGoal_3_match_Ago_InAway,AwayGoal_4_match_Ago_InAway,AwayGoal_5_match_Ago_InAway
0,2025/26,Sabato,23,Agosto,Genoa,Lecce,0,0,False,True,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0
1,2025/26,Sabato,23,Agosto,Sassuolo,Napoli,0,2,False,False,...,2.0,0.0,0.0,0.0,0.0,2.0,0.0,0.0,0.0,0.0
2,2025/26,Sabato,23,Agosto,Milan,Cremonese,1,2,False,False,...,2.0,2.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0,0.0
3,2025/26,Sabato,23,Agosto,Roma,Bologna,1,0,True,False,...,0.0,2.0,2.0,0.0,0.0,0.0,2.0,2.0,0.0,0.0
4,2025/26,Domenica,24,Agosto,Cagliari,Fiorentina,1,1,False,True,...,1.0,0.0,2.0,2.0,0.0,1.0,0.0,2.0,2.0,0.0

In [4]:
squadra = 'Fiorentina'
df = df[['Home', 'Away', 'Result']]
df.query(f'Home == "{squadra}" | Away == "{squadra}"').head(8)

          Home        Away Result
4     Cagliari  Fiorentina      X
17      Torino  Fiorentina      X
22  Fiorentina      Napoli      2
37  Fiorentina        Como      2
44        Pisa  Fiorentina      X
57  Fiorentina        Roma      2
68       Milan  Fiorentina      1
78  Fiorentina     Bologna      X

In [5]:
risultati = []
risultato = '1'  # Example: '1' for home win, '2' for away win, 'X' for draw
matches = df.query(f'Home == "{squadra}" or Away == "{squadra}"')
precedente = 0
for _, row in matches.iterrows():
    risultato = str(row['Result']).strip()
    if risultato == 'X':
        new = precedente
    else:
        if row['Home'] == squadra:
            if risultato == '1':
                new = precedente + 1
            elif risultato == '2':
                new = precedente - 1
            else:
                new = precedente
        else:  # Juventus is away
            if risultato == '2':
                new = precedente + 1
            elif risultato == '1':
                new = precedente - 1
            else:
                new = precedente
    risultati.append(new)
    precedente = new
print(risultati)

[0, 0, -1, -2, -2, -3, -4, -4]

In [6]:

esiti = []

squadraInEsame = df.query(f'Home == "{squadra}" or Away == "{squadra}"')

for _, row in squadraInEsame.iterrows():    #itero la series
    esito = str(row['Result']).strip()  #estraggo l'esito 
    if esito == 'X': # se l'esito è X in casa o trasferta non cambia
        new = 'X'
    else:
        if row['Home'] == squadra:
            if esito == '1':    # se gioca in casa 1 rimane 1 ma va aggiunto alla lista
                new ='1'
            elif esito == '2':  # se gioca in casa e perde resta 2 e va aggiunto alla lista
                new = '2'
            
        else:  # squadra is away
            if esito == '2': # se gioca in trasferta e vince diventa 1
                new = '1'
            elif esito == '1':  # se gioca in trasferta e perde diventa 2
                new = '2'
            
    esiti.append(new)
print(esiti)

['X', 'X', '2', '2', 'X', '2', '2', 'X']